# Generated by Django 5.2.11 on 2026-03-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
