# Generated by Django 5.2.11 on 2026-03-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
